export type ApiManifestEntry = {
  module: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  auth: string;
  backendStatus: "planned" | "implemented" | "blocked" | "deprecated";
  frontendStatus: "pending" | "connected" | "blocked" | "not_needed";
  request: string;
  response: string;
  owner?: string;
  source: string;
  notes?: string;
};

const implemented = "implemented" as const;

function api(entry: Omit<ApiManifestEntry, "backendStatus">): ApiManifestEntry {
  return { backendStatus: implemented, ...entry };
}

const businessSource = "backend/src/services/business-api.service.ts";

export const apiManifest: ApiManifestEntry[] = [
  api({
    module: "auth",
    method: "POST",
    path: "/api/auth/login",
    summary: "Login institucional por codigo de colegio, usuario y contraseña",
    auth: "publico",
    frontendStatus: "pending",
    request: "{ institutionCode, username, password }",
    response: "{ session, authUser, user, institution }",
    source: "backend/src/routes/auth.routes.ts",
    notes: "Resuelve institutions.code + users.username y autentica contra Supabase Auth; Node no almacena contraseñas.",
  }),
  api({
    module: "auth",
    method: "POST",
    path: "/api/auth/refresh",
    summary: "Renueva sesion Supabase usando refresh token",
    auth: "publico",
    frontendStatus: "pending",
    request: "{ refreshToken }",
    response: "{ session, authUser }",
    source: "backend/src/routes/auth.routes.ts",
  }),
  api({
    module: "auth",
    method: "POST",
    path: "/api/auth/recover-password",
    summary: "Solicita recuperación de contraseña por colegio y usuario",
    auth: "publico",
    frontendStatus: "pending",
    request: "{ institutionCode, username }",
    response: "{ ok, message }",
    source: "backend/src/routes/auth.routes.ts",
    notes: "Genera link con Supabase Admin y envia correo via Resend; PASSWORD_RESET_REDIRECT_URL es opcional.",
  }),
  api({
    module: "auth",
    method: "POST",
    path: "/api/auth/logout",
    summary: "Cierra sesion Supabase desde el backend",
    auth: "usuario autenticado",
    frontendStatus: "pending",
    request: "sin body",
    response: "{ ok: true }",
    source: "backend/src/routes/auth.routes.ts",
  }),
  api({
    module: "admin",
    method: "GET",
    path: "/api/admin/institutions",
    summary: "Lista instituciones disponibles para administracion",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "query opcional: search, active",
    response: "Institution[]",
    source: "backend/src/routes/admin.routes.ts",
    notes: "Super admin ve todas y puede filtrar por search/active; admin institucional solo ve su institucion.",
  }),
  api({
    module: "admin",
    method: "POST",
    path: "/api/admin/institutions",
    summary: "Crea institucion",
    auth: "super_admin",
    frontendStatus: "pending",
    request: "{ code, name, commercialName?, subdomain?, email?, phone?, timezone?, active? }",
    response: "{ institution }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "PATCH",
    path: "/api/admin/institutions/:id",
    summary: "Actualiza institucion",
    auth: "admin de la institucion o super_admin",
    frontendStatus: "pending",
    request: "campos parciales de institucion",
    response: "{ institution }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "DELETE",
    path: "/api/admin/institutions/:id",
    summary: "Archiva institucion",
    auth: "super_admin",
    frontendStatus: "pending",
    request: "param id",
    response: "{ institution }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "GET",
    path: "/api/admin/users",
    summary: "Lista usuarios institucionales con roles",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "query opcional: institutionId, search, active",
    response: "User[]",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "POST",
    path: "/api/admin/users",
    summary: "Crea usuario de aplicacion y asigna roles",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "{ institutionId? solo super_admin, email, fullName, username?, personId?, authUserId?, roleCodes? }",
    response: "{ user }",
    source: "backend/src/routes/admin.routes.ts",
    notes: "No crea contraseña; invitacion/credencial Supabase queda en flujo de correo/Auth.",
  }),
  api({
    module: "admin",
    method: "PATCH",
    path: "/api/admin/users/:id",
    summary: "Actualiza usuario institucional y roles",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "campos parciales de usuario; institutionId? solo super_admin; roleCodes? reemplaza roles",
    response: "{ user }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "DELETE",
    path: "/api/admin/users/:id",
    summary: "Archiva usuario institucional",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "param id; query opcional: institutionId solo super_admin",
    response: "{ user }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "GET",
    path: "/api/admin/roles",
    summary: "Lista roles globales e institucionales",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "query opcional: institutionId solo super_admin",
    response: "Role[]",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "POST",
    path: "/api/admin/roles",
    summary: "Crea rol institucional",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "{ institutionId? solo super_admin, name, code, description?, active? }",
    response: "{ role }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "PATCH",
    path: "/api/admin/roles/:id",
    summary: "Actualiza rol institucional no sistemico",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "campos parciales de rol; institutionId? solo super_admin",
    response: "{ role }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "DELETE",
    path: "/api/admin/roles/:id",
    summary: "Desactiva rol institucional no sistemico",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "param id; query opcional: institutionId solo super_admin",
    response: "{ role }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "GET",
    path: "/api/admin/students",
    summary: "Lista estudiantes institucionales",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "query opcional: institutionId solo super_admin, search, active",
    response: "Student[] con persons",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "POST",
    path: "/api/admin/students",
    summary: "Crea estudiante y persona",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "{ institutionId? solo super_admin, firstName, lastName, studentCode, ... }",
    response: "{ student }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "PATCH",
    path: "/api/admin/students/:id",
    summary: "Actualiza estudiante y persona",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "campos parciales; institutionId? solo super_admin",
    response: "{ student }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "DELETE",
    path: "/api/admin/students/:id",
    summary: "Archiva estudiante",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "param id; query opcional: institutionId solo super_admin",
    response: "{ ok: true }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "GET",
    path: "/api/admin/teachers",
    summary: "Lista docentes institucionales",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "query opcional: institutionId solo super_admin, search, active",
    response: "Teacher[] con persons",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "POST",
    path: "/api/admin/teachers",
    summary: "Crea docente y persona",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "{ institutionId? solo super_admin, firstName, lastName, teacherCode, ... }",
    response: "{ teacher }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "PATCH",
    path: "/api/admin/teachers/:id",
    summary: "Actualiza docente y persona",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "campos parciales; institutionId? solo super_admin",
    response: "{ teacher }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "DELETE",
    path: "/api/admin/teachers/:id",
    summary: "Archiva docente",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "param id; query opcional: institutionId solo super_admin",
    response: "{ ok: true }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "GET",
    path: "/api/admin/parents",
    summary: "Lista padres/acudientes institucionales",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "query opcional: institutionId solo super_admin, search",
    response: "Parent[] con persons",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "POST",
    path: "/api/admin/parents",
    summary: "Crea padre/acudiente y persona",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "{ institutionId? solo super_admin, firstName, lastName, occupation?, ... }",
    response: "{ parent }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "PATCH",
    path: "/api/admin/parents/:id",
    summary: "Actualiza padre/acudiente y persona",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "campos parciales; institutionId? solo super_admin",
    response: "{ parent }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "admin",
    method: "DELETE",
    path: "/api/admin/parents/:id",
    summary: "Archiva padre/acudiente",
    auth: "admin, super_admin",
    frontendStatus: "pending",
    request: "param id; query opcional: institutionId solo super_admin",
    response: "{ ok: true }",
    source: "backend/src/routes/admin.routes.ts",
  }),
  api({
    module: "business_api",
    method: "POST",
    path: "/api/business-api",
    summary: "Dispatcher compatible para escrituras sensibles del frontend",
    auth: "usuario autenticado",
    frontendStatus: "connected",
    request: "{ action, payload }",
    response: "{ ok, data }",
    source: "backend/src/routes/business-api.routes.ts",
    notes: "Contrato usado por BackendApiClient; se conserva tambien en /functions/v1/business-api.",
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.teacherClasses",
    summary: "Lista clases del docente para formularios de tareas",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{}",
    response: "ClassSessionBrief[]",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.upsert",
    summary: "Crea o actualiza tarea con reglas de docente y adjuntos",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ assignmentId?, classId, title, description?, instructions?, dueAt, maxScore, allowLate, published?, attachments[] }",
    response: "{ assignment }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.delete",
    summary: "Archiva tarea por soft-delete",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.publish",
    summary: "Publica u oculta una tarea",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id, published }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.submit",
    summary: "Registra entrega de estudiante",
    auth: "student, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ assignmentId, studentId?, attachments[], notes? }",
    response: "{ submission }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.gradeSubmission",
    summary: "Califica una entrega y sincroniza la nota",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ submissionId, score, feedback? }",
    response: "{ submission }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "/api/assignments/*",
    summary: "Rutas REST equivalentes para tareas",
    auth: "teacher/student segun accion",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a las actions assignments.*",
    response: "{ ok, data }",
    source: "backend/src/routes/assignments.routes.ts",
    notes: "Disponibles para clientes nuevos; Flutter usa /api/business-api por compatibilidad.",
  }),
  api({
    module: "attendance",
    method: "POST",
    path: "action: attendance.upsertClassSession",
    summary: "Crea o actualiza sesion de clase para asistencia",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ classId, dateMs }",
    response: "{ id }",
    source: businessSource,
    notes: "Usado por AttendanceSyncService cuando hay backend conectado.",
  }),
  api({
    module: "attendance",
    method: "POST",
    path: "action: attendance.upsertAttendance",
    summary: "Sincroniza marcacion de asistencia",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ uuid, classId, classSessionId, studentId, statusId, recordedAtMs, notes? }",
    response: "{ id }",
    source: businessSource,
    notes: "Usado por AttendanceSyncService para subir marcaciones offline-first.",
  }),
  api({
    module: "attendance",
    method: "POST",
    path: "/api/attendance/*",
    summary: "Rutas REST equivalentes para asistencia",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a attendance.*",
    response: "{ ok, data }",
    source: "backend/src/routes/attendance.routes.ts",
  }),
  api({
    module: "chat",
    method: "POST",
    path: "action: chat.sendMessage",
    summary: "Envia mensaje con texto o adjunto",
    auth: "participante de la conversacion",
    frontendStatus: "connected",
    request: "{ conversationId, content?, attachment? }",
    response: "{ message }",
    source: businessSource,
  }),
  api({
    module: "chat",
    method: "POST",
    path: "action: chat.markAsRead",
    summary: "Marca mensajes de conversacion como leidos",
    auth: "participante de la conversacion",
    frontendStatus: "connected",
    request: "{ conversationId }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "chat",
    method: "POST",
    path: "action: chat.ensureIndividual",
    summary: "Crea o reutiliza conversacion individual",
    auth: "usuario autenticado",
    frontendStatus: "connected",
    request: "{ otherUserId }",
    response: "{ conversationId }",
    source: businessSource,
  }),
  api({
    module: "chat",
    method: "POST",
    path: "/api/chats/*",
    summary: "Rutas REST equivalentes para chat",
    auth: "usuario autenticado",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a chat.*",
    response: "{ ok, data }",
    source: "backend/src/routes/chats.routes.ts",
  }),
  api({
    module: "events",
    method: "POST",
    path: "action: events.create",
    summary: "Crea evento o anuncio de calendario",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ title, description, date, audience }",
    response: "{ event }",
    source: businessSource,
    notes: "Tambien crea notificaciones para la audiencia y llama send-push si INTERNAL_API_SECRET esta configurado.",
  }),
  api({
    module: "events",
    method: "POST",
    path: "/api/events",
    summary: "Ruta REST equivalente para crear evento",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "not_needed",
    request: "{ title, description, date, audience }",
    response: "{ event }",
    source: "backend/src/routes/events.routes.ts",
  }),
  api({
    module: "grades",
    method: "POST",
    path: "action: grades.upsertScale",
    summary: "Crea o actualiza escala de calificacion",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id?, name, type, minValue, maxValue, passValue, decimals, ranges[] }",
    response: "{ scale }",
    source: businessSource,
  }),
  api({
    module: "grades",
    method: "POST",
    path: "action: grades.setDefaultScale",
    summary: "Define escala institucional por defecto",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "grades",
    method: "POST",
    path: "action: grades.setGrade",
    summary: "Registra o actualiza nota de estudiante",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ evaluationId, studentId, rawScore, notes? }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "grades",
    method: "POST",
    path: "/api/grades/*",
    summary: "Rutas REST equivalentes para notas",
    auth: "admin/teacher segun accion",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a grades.*",
    response: "{ ok, data }",
    source: "backend/src/routes/grades.routes.ts",
  }),
  api({
    module: "notifications",
    method: "POST",
    path: "action: notifications.saveWebPushDevice",
    summary: "Guarda suscripcion Web Push del usuario",
    auth: "usuario autenticado",
    frontendStatus: "connected",
    request: "{ endpoint, pushToken }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "files",
    method: "GET",
    path: "/api/files",
    summary: "Lista metadatos de archivos de la institucion",
    auth: "usuario autenticado",
    frontendStatus: "pending",
    request: "sin body",
    response: "File[]",
    source: "backend/src/routes/files.routes.ts",
  }),
  api({
    module: "files",
    method: "POST",
    path: "/api/files/prepare-upload",
    summary: "Prepara subida firmada a Supabase Storage",
    auth: "usuario autenticado",
    frontendStatus: "pending",
    request: "{ originalName, mimeType, sizeBytes, folder? }",
    response: "{ bucket, storagePath, signedUpload, maxBytes, allowedMimeTypes }",
    source: "backend/src/routes/files.routes.ts",
    notes: "Valida MIME/tamaño y fuerza ruta {institution_id}/...",
  }),
  api({
    module: "files",
    method: "POST",
    path: "/api/files/metadata",
    summary: "Registra metadatos de archivo subido",
    auth: "usuario autenticado",
    frontendStatus: "pending",
    request: "{ originalName, storagePath, mimeType, sizeBytes, url? }",
    response: "{ file }",
    source: "backend/src/routes/files.routes.ts",
  }),
  api({
    module: "reports",
    method: "GET",
    path: "/api/reports/report-cards/preview",
    summary: "Previsualiza boletin calculado desde period_grades",
    auth: "admin/teacher o estudiante/padre propio",
    frontendStatus: "pending",
    request: "query: studentId, academicPeriodId",
    response: "{ student, academicPeriodId, calculation, overallAverage, lines }",
    source: "backend/src/routes/reports.routes.ts",
    notes: "Calculo oficial MVP: promedio aritmetico simple de period_grades.final_score.",
  }),
  api({
    module: "reports",
    method: "POST",
    path: "/api/reports/report-cards",
    summary: "Genera y persiste boletin academico",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "pending",
    request: "{ studentId, academicPeriodId, generalNotes? }",
    response: "{ reportCard }",
    source: "backend/src/routes/reports.routes.ts",
    notes: "PDF binario queda fuera del MVP hasta definir plantilla/proveedor; devuelve pdfStatus.",
  }),
  api({
    module: "reports",
    method: "GET",
    path: "/api/reports/report-cards/:id",
    summary: "Obtiene boletin generado",
    auth: "admin/teacher o estudiante/padre propio",
    frontendStatus: "pending",
    request: "param id",
    response: "{ reportCard }",
    source: "backend/src/routes/reports.routes.ts",
  }),
  api({
    module: "notifications",
    method: "POST",
    path: "/api/notifications/web-push-device",
    summary: "Ruta REST equivalente para guardar dispositivo Web Push",
    auth: "usuario autenticado",
    frontendStatus: "not_needed",
    request: "{ endpoint, pushToken }",
    response: "{ ok: true }",
    source: "backend/src/routes/notifications.routes.ts",
  }),
  api({
    module: "payments",
    method: "POST",
    path: "action: payments.register",
    summary: "Registra pago contra cargo",
    auth: "parent, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ chargeId, amount, method, payerName?, reference?, gatewayName?, idempotencyKey? }",
    response: "{ payment }",
    source: businessSource,
    notes: "Pendiente integrar proveedor real e idempotencia de pasarela.",
  }),
  api({
    module: "sync",
    method: "GET",
    path: "/api/sync/queue",
    summary: "Lista operaciones offline de asistencia del profesor",
    auth: "teacher",
    frontendStatus: "pending",
    request: "query opcional: status",
    response: "sync_queue[]",
    source: "backend/src/routes/sync.routes.ts",
    notes: "Offline sync queda limitado a profesores tomando asistencia sin internet/luz.",
  }),
  api({
    module: "sync",
    method: "POST",
    path: "/api/sync/queue",
    summary: "Encola asistencia offline para subir al recuperar conexion",
    auth: "teacher",
    frontendStatus: "pending",
    request: "{ tableName: attendances|class_sessions, operation: insert|update|upsert, recordUuid?, payload, clientTimestamp? }",
    response: "{ item }",
    source: "backend/src/routes/sync.routes.ts",
    notes: "Solo para profesor tomando asistencia; el registro se guarda localmente en el telefono y se sube cuando vuelva la conexion.",
  }),
  api({
    module: "sync",
    method: "POST",
    path: "/api/sync/queue/:id/retry",
    summary: "Marca asistencia offline para reintento",
    auth: "teacher",
    frontendStatus: "pending",
    request: "param id",
    response: "{ item }",
    source: "backend/src/routes/sync.routes.ts",
  }),
  api({
    module: "sync",
    method: "POST",
    path: "/api/sync/queue/:id/failed",
    summary: "Marca asistencia offline como fallida",
    auth: "teacher",
    frontendStatus: "pending",
    request: "{ error? }",
    response: "{ item }",
    source: "backend/src/routes/sync.routes.ts",
  }),
  api({
    module: "sync",
    method: "GET",
    path: "/api/sync/changes",
    summary: "Lista cambios de asistencia desde una fecha",
    auth: "teacher",
    frontendStatus: "pending",
    request: "query opcional: since",
    response: "{ serverTime, changes, conflictPolicy, scope }",
    source: "backend/src/routes/sync.routes.ts",
    notes: "Politica: teacher_attendance_upload_only. No se usa para pagos, chat, tareas o calificaciones.",
  }),
  api({
    module: "payments",
    method: "POST",
    path: "action: payments.cancelCharge",
    summary: "Anula cargo desde administracion",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ chargeId }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "payments",
    method: "POST",
    path: "/api/payments/*",
    summary: "Rutas REST equivalentes para pagos",
    auth: "parent/admin segun accion",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a payments.*",
    response: "{ ok, data }",
    source: "backend/src/routes/payments.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/summary",
    summary: "Resumen operativo del dashboard tecnico",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "{ counts, pendingTasks, recentAuditEvents }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/institutions",
    summary: "Lista instituciones visibles por RLS",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "Institution[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/users",
    summary: "Lista usuarios visibles por RLS",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: institutionId, search, active",
    response: "User[] con roles",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/audit-events",
    summary: "Lista auditoria tecnica del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "DeveloperAuditEvent[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/modules",
    summary: "Lista modulos configurables del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: moduleKey",
    response: "DeveloperDashboardModule[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/modules",
    summary: "Crea modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ moduleKey, title, description?, category?, icon?, frontendRoute?, enabled? }",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/modules/:id",
    summary: "Actualiza modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del modulo",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/modules/:id",
    summary: "Archiva modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/apis",
    summary: "Lista APIs registradas para conectar",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: moduleKey, backendStatus, frontendStatus",
    response: "DeveloperApiRegistry[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/apis",
    summary: "Crea registro en inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ moduleKey, method, path, summary, action?, requestSchema?, responseSchema? }",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/apis/:id",
    summary: "Actualiza registro del inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del registro API",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/apis/:id",
    summary: "Archiva registro del inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/tasks",
    summary: "Lista tareas tecnicas del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: moduleKey, status",
    response: "DeveloperTask[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/tasks",
    summary: "Crea tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ title, moduleKey?, description?, priority?, owner? }",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/tasks/:id",
    summary: "Actualiza tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales de la tarea",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/tasks/:id",
    summary: "Archiva tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/feature-flags",
    summary: "Lista feature flags",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: enabled",
    response: "DeveloperFeatureFlag[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/feature-flags",
    summary: "Crea feature flag",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ flagKey, title, description?, enabled?, rolloutPercent?, config? }",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/feature-flags/:id",
    summary: "Actualiza feature flag",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del flag",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/feature-flags/:id",
    summary: "Archiva feature flag",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/system-checks",
    summary: "Lista checks de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: status, severity",
    response: "DeveloperSystemCheck[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/system-checks",
    summary: "Crea check de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ checkKey, title, checkType?, target?, severity? }",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/system-checks/:id",
    summary: "Actualiza check de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del check",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/system-checks/:id",
    summary: "Archiva check de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
];

