export type ApiManifestEntry = {
  module: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  auth: string;
  backendStatus: "planned" | "implemented" | "blocked" | "deprecated";
  frontendStatus: "pending" | "connected" | "blocked" | "not_needed";
  request: string;
  response: string;
  owner?: string;
  source: string;
  notes?: string;
};

const implemented = "implemented" as const;

function api(entry: Omit<ApiManifestEntry, "backendStatus">): ApiManifestEntry {
  return { backendStatus: implemented, ...entry };
}

const businessSource = "backend/src/services/business-api.service.ts";

export const apiManifest: ApiManifestEntry[] = [
  api({
    module: "business_api",
    method: "POST",
    path: "/api/business-api",
    summary: "Dispatcher compatible para escrituras sensibles del frontend",
    auth: "usuario autenticado",
    frontendStatus: "connected",
    request: "{ action, payload }",
    response: "{ ok, data }",
    source: "backend/src/routes/business-api.routes.ts",
    notes: "Contrato usado por BackendApiClient; se conserva tambien en /functions/v1/business-api.",
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.teacherClasses",
    summary: "Lista clases del docente para formularios de tareas",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{}",
    response: "ClassSessionBrief[]",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.upsert",
    summary: "Crea o actualiza tarea con reglas de docente y adjuntos",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ assignmentId?, classId, title, description?, instructions?, dueAt, maxScore, allowLate, published?, attachments[] }",
    response: "{ assignment }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.delete",
    summary: "Archiva tarea por soft-delete",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.publish",
    summary: "Publica u oculta una tarea",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id, published }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.submit",
    summary: "Registra entrega de estudiante",
    auth: "student, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ assignmentId, studentId?, attachments[], notes? }",
    response: "{ submission }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "action: assignments.gradeSubmission",
    summary: "Califica una entrega y sincroniza la nota",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ submissionId, score, feedback? }",
    response: "{ submission }",
    source: businessSource,
  }),
  api({
    module: "assignments",
    method: "POST",
    path: "/api/assignments/*",
    summary: "Rutas REST equivalentes para tareas",
    auth: "teacher/student segun accion",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a las actions assignments.*",
    response: "{ ok, data }",
    source: "backend/src/routes/assignments.routes.ts",
    notes: "Disponibles para clientes nuevos; Flutter usa /api/business-api por compatibilidad.",
  }),
  api({
    module: "attendance",
    method: "POST",
    path: "action: attendance.upsertClassSession",
    summary: "Crea o actualiza sesion de clase para asistencia",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ classId, dateMs }",
    response: "{ id }",
    source: businessSource,
    notes: "Usado por AttendanceSyncService cuando hay backend conectado.",
  }),
  api({
    module: "attendance",
    method: "POST",
    path: "action: attendance.upsertAttendance",
    summary: "Sincroniza marcacion de asistencia",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ uuid, classId, classSessionId, studentId, statusId, recordedAtMs, notes? }",
    response: "{ id }",
    source: businessSource,
    notes: "Usado por AttendanceSyncService para subir marcaciones offline-first.",
  }),
  api({
    module: "attendance",
    method: "POST",
    path: "/api/attendance/*",
    summary: "Rutas REST equivalentes para asistencia",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a attendance.*",
    response: "{ ok, data }",
    source: "backend/src/routes/attendance.routes.ts",
  }),
  api({
    module: "chat",
    method: "POST",
    path: "action: chat.sendMessage",
    summary: "Envia mensaje con texto o adjunto",
    auth: "participante de la conversacion",
    frontendStatus: "connected",
    request: "{ conversationId, content?, attachment? }",
    response: "{ message }",
    source: businessSource,
  }),
  api({
    module: "chat",
    method: "POST",
    path: "action: chat.markAsRead",
    summary: "Marca mensajes de conversacion como leidos",
    auth: "participante de la conversacion",
    frontendStatus: "connected",
    request: "{ conversationId }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "chat",
    method: "POST",
    path: "action: chat.ensureIndividual",
    summary: "Crea o reutiliza conversacion individual",
    auth: "usuario autenticado",
    frontendStatus: "connected",
    request: "{ otherUserId }",
    response: "{ conversationId }",
    source: businessSource,
  }),
  api({
    module: "chat",
    method: "POST",
    path: "/api/chats/*",
    summary: "Rutas REST equivalentes para chat",
    auth: "usuario autenticado",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a chat.*",
    response: "{ ok, data }",
    source: "backend/src/routes/chats.routes.ts",
  }),
  api({
    module: "events",
    method: "POST",
    path: "action: events.create",
    summary: "Crea evento o anuncio de calendario",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ title, description, date, audience }",
    response: "{ event }",
    source: businessSource,
  }),
  api({
    module: "events",
    method: "POST",
    path: "/api/events",
    summary: "Ruta REST equivalente para crear evento",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "not_needed",
    request: "{ title, description, date, audience }",
    response: "{ event }",
    source: "backend/src/routes/events.routes.ts",
  }),
  api({
    module: "grades",
    method: "POST",
    path: "action: grades.upsertScale",
    summary: "Crea o actualiza escala de calificacion",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id?, name, type, minValue, maxValue, passValue, decimals, ranges[] }",
    response: "{ scale }",
    source: businessSource,
  }),
  api({
    module: "grades",
    method: "POST",
    path: "action: grades.setDefaultScale",
    summary: "Define escala institucional por defecto",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ id }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "grades",
    method: "POST",
    path: "action: grades.setGrade",
    summary: "Registra o actualiza nota de estudiante",
    auth: "teacher, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ evaluationId, studentId, rawScore, notes? }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "grades",
    method: "POST",
    path: "/api/grades/*",
    summary: "Rutas REST equivalentes para notas",
    auth: "admin/teacher segun accion",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a grades.*",
    response: "{ ok, data }",
    source: "backend/src/routes/grades.routes.ts",
  }),
  api({
    module: "notifications",
    method: "POST",
    path: "action: notifications.saveWebPushDevice",
    summary: "Guarda suscripcion Web Push del usuario",
    auth: "usuario autenticado",
    frontendStatus: "connected",
    request: "{ endpoint, pushToken }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "notifications",
    method: "POST",
    path: "/api/notifications/web-push-device",
    summary: "Ruta REST equivalente para guardar dispositivo Web Push",
    auth: "usuario autenticado",
    frontendStatus: "not_needed",
    request: "{ endpoint, pushToken }",
    response: "{ ok: true }",
    source: "backend/src/routes/notifications.routes.ts",
  }),
  api({
    module: "payments",
    method: "POST",
    path: "action: payments.register",
    summary: "Registra pago contra cargo",
    auth: "parent, admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ chargeId, amount, method, payerName?, reference?, gatewayName?, idempotencyKey? }",
    response: "{ payment }",
    source: businessSource,
    notes: "Pendiente integrar proveedor real e idempotencia de pasarela.",
  }),
  api({
    module: "payments",
    method: "POST",
    path: "action: payments.cancelCharge",
    summary: "Anula cargo desde administracion",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ chargeId }",
    response: "{ ok: true }",
    source: businessSource,
  }),
  api({
    module: "payments",
    method: "POST",
    path: "/api/payments/*",
    summary: "Rutas REST equivalentes para pagos",
    auth: "parent/admin segun accion",
    frontendStatus: "not_needed",
    request: "payloads equivalentes a payments.*",
    response: "{ ok, data }",
    source: "backend/src/routes/payments.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/summary",
    summary: "Resumen operativo del dashboard tecnico",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "{ counts, pendingTasks, recentAuditEvents }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/institutions",
    summary: "Lista instituciones visibles por RLS",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "Institution[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/users",
    summary: "Lista usuarios visibles por RLS",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "User[] con roles",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/audit-events",
    summary: "Lista auditoria tecnica del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "sin body",
    response: "DeveloperAuditEvent[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/modules",
    summary: "Lista modulos configurables del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: moduleKey",
    response: "DeveloperDashboardModule[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/modules",
    summary: "Crea modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ moduleKey, title, description?, category?, icon?, frontendRoute?, enabled? }",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/modules/:id",
    summary: "Actualiza modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del modulo",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/modules/:id",
    summary: "Archiva modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/apis",
    summary: "Lista APIs registradas para conectar",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: moduleKey, backendStatus, frontendStatus",
    response: "DeveloperApiRegistry[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/apis",
    summary: "Crea registro en inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ moduleKey, method, path, summary, action?, requestSchema?, responseSchema? }",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/apis/:id",
    summary: "Actualiza registro del inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del registro API",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/apis/:id",
    summary: "Archiva registro del inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/tasks",
    summary: "Lista tareas tecnicas del dashboard",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: moduleKey, status",
    response: "DeveloperTask[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/tasks",
    summary: "Crea tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ title, moduleKey?, description?, priority?, owner? }",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/tasks/:id",
    summary: "Actualiza tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales de la tarea",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/tasks/:id",
    summary: "Archiva tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/feature-flags",
    summary: "Lista feature flags",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: enabled",
    response: "DeveloperFeatureFlag[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/feature-flags",
    summary: "Crea feature flag",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ flagKey, title, description?, enabled?, rolloutPercent?, config? }",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/feature-flags/:id",
    summary: "Actualiza feature flag",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del flag",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/feature-flags/:id",
    summary: "Archiva feature flag",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
  api({
    module: "developer",
    method: "GET",
    path: "/api/developer/system-checks",
    summary: "Lista checks de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "query opcional: status, severity",
    response: "DeveloperSystemCheck[]",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "POST",
    path: "/api/developer/system-checks",
    summary: "Crea check de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "{ checkKey, title, checkType?, target?, severity? }",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "PATCH",
    path: "/api/developer/system-checks/:id",
    summary: "Actualiza check de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "campos parciales del check",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
  }),
  api({
    module: "developer",
    method: "DELETE",
    path: "/api/developer/system-checks/:id",
    summary: "Archiva check de sistema",
    auth: "admin, coordinator, director, super_admin",
    frontendStatus: "connected",
    request: "param id",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  }),
];
