export type ApiManifestEntry = {
  module: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
  summary: string;
  auth: string;
  backendStatus: "planned" | "implemented" | "blocked" | "deprecated";
  frontendStatus: "pending" | "connected" | "blocked" | "not_needed";
  request: string;
  response: string;
  owner?: string;
  source: string;
  notes?: string;
};

export const apiManifest: ApiManifestEntry[] = [
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/summary",
    summary: "Resumen operativo del dashboard tecnico",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "query opcional vacio",
    response: "{ counts, pendingTasks, recentAuditEvents }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Pendiente conectar a una pantalla principal del dashboard de desarrollador.",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/institutions",
    summary: "Lista instituciones visibles por RLS",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "sin body",
    response: "Institution[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/users",
    summary: "Lista usuarios visibles por RLS",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "sin body",
    response: "User[] con roles",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/audit-events",
    summary: "Lista auditoria tecnica del dashboard",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "sin body",
    response: "DeveloperAuditEvent[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/modules",
    summary: "Lista modulos configurables del dashboard",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "query opcional: moduleKey",
    response: "DeveloperDashboardModule[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "POST",
    path: "/api/developer/modules",
    summary: "Crea modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "{ moduleKey, title, description?, category?, icon?, frontendRoute?, enabled? }",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "PATCH",
    path: "/api/developer/modules/:id",
    summary: "Actualiza modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "campos parciales del modulo",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "DELETE",
    path: "/api/developer/modules/:id",
    summary: "Archiva modulo configurable del dashboard",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "param id",
    response: "{ module }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/apis",
    summary: "Lista APIs registradas para conectar",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "query opcional: moduleKey, backendStatus, frontendStatus",
    response: "DeveloperApiRegistry[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "POST",
    path: "/api/developer/apis",
    summary: "Crea registro en inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "{ moduleKey, method, path, summary, action?, requestSchema?, responseSchema? }",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "PATCH",
    path: "/api/developer/apis/:id",
    summary: "Actualiza registro del inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "campos parciales del registro API",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "DELETE",
    path: "/api/developer/apis/:id",
    summary: "Archiva registro del inventario de APIs",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "param id",
    response: "{ api }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/tasks",
    summary: "Lista tareas tecnicas del dashboard",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "query opcional: moduleKey, status",
    response: "DeveloperTask[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "POST",
    path: "/api/developer/tasks",
    summary: "Crea tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "{ title, moduleKey?, description?, priority?, owner? }",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "PATCH",
    path: "/api/developer/tasks/:id",
    summary: "Actualiza tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "campos parciales de la tarea",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "DELETE",
    path: "/api/developer/tasks/:id",
    summary: "Archiva tarea tecnica",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "param id",
    response: "{ task }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/feature-flags",
    summary: "Lista feature flags",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "query opcional: enabled",
    response: "DeveloperFeatureFlag[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "POST",
    path: "/api/developer/feature-flags",
    summary: "Crea feature flag",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "{ flagKey, title, description?, enabled?, rolloutPercent?, config? }",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "PATCH",
    path: "/api/developer/feature-flags/:id",
    summary: "Actualiza feature flag",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "campos parciales del flag",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "DELETE",
    path: "/api/developer/feature-flags/:id",
    summary: "Archiva feature flag",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "param id",
    response: "{ featureFlag }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  },
  {
    module: "developer",
    method: "GET",
    path: "/api/developer/system-checks",
    summary: "Lista checks de sistema",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "query opcional: status, severity",
    response: "DeveloperSystemCheck[]",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "POST",
    path: "/api/developer/system-checks",
    summary: "Crea check de sistema",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "{ checkKey, title, checkType?, target?, severity? }",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "PATCH",
    path: "/api/developer/system-checks/:id",
    summary: "Actualiza check de sistema",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "campos parciales del check",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
  },
  {
    module: "developer",
    method: "DELETE",
    path: "/api/developer/system-checks/:id",
    summary: "Archiva check de sistema",
    auth: "admin, coordinator, director, super_admin",
    backendStatus: "implemented",
    frontendStatus: "pending",
    request: "param id",
    response: "{ systemCheck }",
    source: "backend/src/routes/developer.routes.ts",
    notes: "Soft-delete: marca deleted_at.",
  },
];
